"""added user_id to tutor model

Revision ID: a54b0b989a7d
Revises: 
Create Date: 2023-11-06 19:17:59.264356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a54b0b989a7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tutor_student')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('username')

    op.drop_table('user')
    op.drop_table('student_subjects')
    op.drop_table('family')
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.alter_column('tutor_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('weekday_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('start_time',
               existing_type=mysql.TIME(),
               nullable=False)
        batch_op.alter_column('end_time',
               existing_type=mysql.TIME(),
               nullable=False)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint('student_ibfk_1', type_='foreignkey')
        batch_op.drop_column('family_id')

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.alter_column('schooltype_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('tutors', schema=None) as batch_op:
        batch_op.drop_column('password_hash')
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', mysql.VARCHAR(length=50), server_default=sa.text("'tutor'"), nullable=True))
        batch_op.add_column(sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True))

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.alter_column('schooltype_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('student_ibfk_1', 'family', ['family_id'], ['id'])

    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=mysql.TIME(),
               nullable=True)
        batch_op.alter_column('start_time',
               existing_type=mysql.TIME(),
               nullable=True)
        batch_op.alter_column('weekday_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('tutor_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    op.create_table('family',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('student_subjects',
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.StudentID'], name='student_subjects_ibfk_1'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], name='student_subjects_ibfk_2'),
    sa.PrimaryKeyConstraint('student_id', 'subject_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='user_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=False)

    op.create_table('tutor_student',
    sa.Column('tutor_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.StudentID'], name='tutor_student_ibfk_2'),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.tutor_id'], name='tutor_student_ibfk_1'),
    sa.PrimaryKeyConstraint('tutor_id', 'student_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
